tps : &tps 2000
total : &total 10000

test:
    name: base-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 4
    rounds:
      - label: set
        txNumber: *total
        rateControl: 
          type: fixed-rate
          opts:
            tps: *tps
        workload:
          module: caliper_config/set.js
          arguments:
            assets: 10
            contractId: base

      - label: get
        txNumber: *total
        rateControl: 
          type: fixed-rate
          opts:
            tps: *tps
        workload:
          module: caliper_config/get.js
          arguments:
            assets: 10
            contractId: base
      - label: transfer
        txNumber: *total
        rateControl: 
          type: fixed-rate
          opts:
            tps: *tps
        workload:
          module: caliper_config/transfer.js
          arguments:
            assets: 10
            contractId: base

      # - label: add
      #   txNumber: *total
      #   rateControl: 
      #     type: fixed-rate
      #     opts:
      #       tps: *tps
      #     # type: fixed-load
      #     # opts:
      #     #   transactionLoad: 2
      #   workload:
      #     module: caliper_config/add.js
      #     arguments:
      #       assets: 10
      #       contractId: base

      # - label: mul
      #   txNumber: *total
      #   rateControl: 
      #     type: fixed-rate
      #     opts:
      #       tps: *tps
      #   workload:
      #     module: caliper_config/mul.js
      #     arguments:
      #       assets: 10
      #       contractId: base

      # - label: div
      #   txNumber: *total
      #   rateControl: 
      #     type: fixed-rate
      #     opts:
      #       tps: *tps
      #   workload:
      #     module: caliper_config/div.js
      #     arguments:
      #       assets: 10
      #       contractId: base     

      # - label: fib
      #   txNumber: *total
      #   rateControl: 
      #     type: fixed-rate
      #     opts:
      #       tps: *tps
      #   workload:
      #     module: caliper_config/fib.js
      #     arguments:
      #       assets: 10
      #       contractId: base

monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers:
      - all