services:
  orderer.aaa.com:
    container_name: orderer.aaa.com
    image: hyperledger/fabric-orderer:2.2
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/aaa.com/orderers/orderer.aaa.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/aaa.com/orderers/orderer.aaa.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    command: orderer
  peer0.org1.aaa.com:
    container_name: peer0.org1.aaa.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.aaa.com
      - CORE_PEER_ADDRESS=peer0.org1.aaa.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.aaa.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.aaa.com:7051      
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.aaa.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.aaa.com/peers/peer0.org1.aaa.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.aaa.com/peers/peer0.org1.aaa.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052 
    command: peer node start
  peer0.org2.aaa.com:
    container_name: peer0.org2.aaa.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org2.aaa.com
      - CORE_PEER_ADDRESS=peer0.org2.aaa.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.aaa.com:7061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.aaa.com:7061      
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.aaa.com:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.aaa.com/peers/peer0.org2.aaa.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.aaa.com/peers/peer0.org2.aaa.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7061:7061
      - 7062:7062 
    command: peer node start
  peer0.org3.aaa.com:
    container_name: peer0.org3.aaa.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org3.aaa.com
      - CORE_PEER_ADDRESS=peer0.org3.aaa.com:7071
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7071
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.aaa.com:7071
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.aaa.com:7071      
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.aaa.com:7072
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7072
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.aaa.com/peers/peer0.org3.aaa.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.aaa.com/peers/peer0.org3.aaa.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7071:7071
      - 7072:7072 
    command: peer node start
  peer0.org4.aaa.com:
    container_name: peer0.org4.aaa.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org4.aaa.com
      - CORE_PEER_ADDRESS=peer0.org4.aaa.com:7081
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7081
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.aaa.com:7081
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.aaa.com:7081      
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.aaa.com:7082
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7082
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.aaa.com/peers/peer0.org4.aaa.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.aaa.com/peers/peer0.org4.aaa.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7081:7081
      - 7082:7082 
    command: peer node start
